#!/usr/bin/env bash
# A bash script that configures an ubuntu server to ressolve ip address
# local host to 127.0.0.2
#facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
